pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Builded'
            }
        }
        stage('Test') {
            steps {
                echo 'tested !'
            }
            post {
                always {
                    echo 'posted'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'delivered !'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!' 
            }
        }
    }
}
